# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# ---- 1. basic configuration

title: Lelinahs-Blog # Blog-Name
SEOTitle: Lelinahs-Blog # Browser Registerkarten titel
header-img: img/tag-bg.jpg # Hintergrung Bildung auf Home-page
email: schalk.lea@gmail.com # Email wird im About Me bereich angeziegt
description: Quote learning # Blog-Beschreibung wird nicht angezeigt
keyword: "Learning, Inspiration, Fashion, Food, Languages, Diversity, Start, Progresss, Personal Growth" # Index-Schlüssel Wörter des Blogs
url: "http://lelinah.github.io" # Git hub name des Repo-Kontos
baseurl: "" # can be ignored：for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/lelinah/lelinah.github.io.git" # voller Name des GitHub repository, unbedingt .git hinzufügen




# ---- 2、sidebar configuration

sidebar: true # if u eant sidebar or not
sidebar-about-description: "Hi. My name is Lea. " # a dicription about yourself
sidebar-avatar: /img/my_head_icon.png # location of avatar image

# ---- 3、social links configuration

RSS: false  # enable or disable RSS feeds

# weibo_username:     #######    # weibo
linkedin_username:     Lea Schalk      # Linked in Link
#github_username:    Lelinah      # GitHub
facebook_username:  Lelinahs-Blog      # Facebook
instagram_username:   lelinahsblog  # Instagram
# twitter_username:   ########    # Twitter
#more socail accounts can be added in _include/footer.html

# featured Tags

featured-tags: true               # use or dont use homepage tags
featured-condition-size: 0        # if mentioned once or more, tag will be listed on right side ofe Home-page
featured-condition-size-2: 1
#collection of postst: projects
collections:
  projects:
    output: true

#Intrests

interests: [
    {
        title: "Fashion",              # name to be displaces
       # href: "http://foo.github.io/"   # link to other blog
    },
    {
        title: "Hip Hop",             
       # href: "http://bar.github.io"   
    },
    {
	    title: "Salsa",	
    },
    { 
	    title: "Bachata",                                                                                                                          title: "Salsa"
    }

    # if adding more: syntax needs "," after last "}"
]

#New posts 

newPosts: [
        {
            post:                 # Name of newest post
        },
            post:                 # Name of second newest post
]

# ---- 4、build the configuration

# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty   # 
paginate: 10  # number of blog post per page
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"] # Jekyll framework system configuration
anchorjs: true  # if you want to customize anchor. check out line:181 of `post.html`

# the following configurations are not a necessarity

# Gems #  The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM   # use Github Flavored Markdown !important

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# ---- 5、plug-in configurations (may require some programming knowlege, but try it) 

# commenting section is not jet enabled, availabe in "commenting System" section in README
# Gitalk
gitalk:
  enable: true
  clientID: e2eded4437b43595fffb # cliendID github Application
  clientSecret: 828d8ac74f00f874e70dd182f6f9d754f9b5f364 #cliendSecret aus OAuth github
  repo: lelinah.github.io # storage gitalk's repository
  owner: Lelinah # repo wpner
  admin: Lelinah # repo woner and collaborators, only these guys can initialize github issues

# Disqus（https://disqus.com/）
# disqus_username: zhangsan

# static website analysis

# Baidu Analytics
# ba_track_id: <your track id> # 自己去百度统计注册，把你注册的track_id填这里

# Google Analytics
# ga_track_id: 'UA-xxxxxx-xx' # if you register with google account it will give u an id，Format: UA-xxxxxx-xx
# ga_domain: zhangsan.top     # fill in custom domain name

